#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################
# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+DFT_R3\
     -f ../filelist/filelist_DFT_r3.f

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.FFT_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/clock
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/reset
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_ready
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_0_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_0_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_1_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_1_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_2_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_in_2_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_validate
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_0_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_0_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_1_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_1_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_2_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/io_out_2_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_io_out_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_1_io_out_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_2_io_out_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMult_reducable_io_out_s_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMult_reducable_1_io_out_s_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMult_reducable_2_io_out_s_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMult_reducable_3_io_out_s_Re

#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_io_in_0_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_io_in_1_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder_io_in_2_Re
#
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/FPComplexAdder_io_out_s_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/FPComplexAdder_1_io_out_s_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/io_out_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/io_in_0_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/io_in_1_Re
#add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_DFT_r3/FPComplexMultiAdder/io_in_2_Re

run 1ms                                                                             
                                                                                     
