#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################
# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+FFT_MR36_BASIC\
     -f ../filelist/filelist_FFT_mr36_basic.f

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.FFT_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/clock
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/reset
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_ready
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_0_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_0_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_1_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_1_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_2_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_2_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_3_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_3_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_4_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_4_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_5_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_5_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_6_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_6_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_7_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_7_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_8_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_8_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_9_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_9_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_10_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_10_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_11_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_11_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_12_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_12_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_13_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_13_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_14_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_14_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_15_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_15_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_16_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_16_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_17_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_17_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_18_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_18_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_19_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_19_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_20_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_20_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_21_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_21_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_22_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_22_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_23_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_23_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_24_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_24_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_25_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_25_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_26_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_26_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_27_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_27_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_28_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_28_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_29_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_29_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_30_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_30_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_31_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_31_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_32_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_32_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_33_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_33_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_34_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_34_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_35_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_in_35_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_validate
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_0_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_0_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_1_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_1_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_2_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_2_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_3_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_3_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_4_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_4_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_5_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_5_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_6_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_6_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_7_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_7_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_8_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_8_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_9_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_9_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_10_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_10_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_11_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_11_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_12_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_12_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_13_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_13_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_14_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_14_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_15_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_15_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_16_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_16_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_17_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_17_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_18_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_18_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_19_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_19_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_20_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_20_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_21_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_21_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_22_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_22_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_23_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_23_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_24_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_24_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_25_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_25_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_26_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_26_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_27_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_27_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_28_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_28_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_29_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_29_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_30_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_30_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_31_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_31_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_32_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_32_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_33_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_33_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_34_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_34_Im
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_35_Re
add wave -noupdate -format logic -radix hexadecimal FFT_tb/u_FFT_mr36_basic/io_out_35_Im

run 1ms                                                                             
