#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################
# check if current dir has modelsim config file
#set has_config  [file exists modelsim.do]
## config modelsim 
#if {$has_config==1} { do modelsim.do  ; }
##if {$has_config==1} { do modelsim.do   }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+THD_FFT96_32_48\
     -f ../filelist/filelist_thd_fft96_32_48.f


echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
#vsim -wlf tb.wlf
#vsim -l ./thd_fft96_32_48/thd_fft96_32_48_v3.log -wlf ./thd_fft96_32_48/thd_fft96_32_48_v3.wlf -voptargs=+acc work.thd_fft96_tb -t 1ns
vsim -l ./thd_fft96_32_48/thd_fft96_32_48_v1.log -voptargs=+acc work.thd_fft96_tb -t 1ns

add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/clock  
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/reset  
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_in_0_Re   
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_in_0_Im   
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_in_1_Re   
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_in_1_Im   
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_out_validate
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_out_0_Re  
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_out_0_Im  
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_out_1_Re  
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/io_out_1_Im  

add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_rdy 
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_od_vld      
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_td_rdy      
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_td_vld      
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_thd_rdy      
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_thd_vld      
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st0_out_vld 
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt0_en 
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt0 

add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_rdy 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_od_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_td_rdy      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_td_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_thd_rdy      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_thd_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st1_out_vld 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt1_en 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt1 

add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_rdy 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_od_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_td_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_td_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_thd_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_thd_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st2_out_vld 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt2_en 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt2 

add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_rdy 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_od_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_td_rdy      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_td_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_thd_rdy      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_thd_vld      
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st3_out_vld 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt3_en 
add wave -color green -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt3 

add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_rdy 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_od_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_td_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_td_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_thd_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_thd_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st4_out_vld 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt4_en 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt4 

add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_rdy 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_od_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_td_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_td_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_thd_rdy      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_thd_vld      
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/st5_out_vld 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt5_en 
add wave -color orange -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/cnt5 

add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_wr
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_rd
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_wraddr0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_wraddr1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_rdaddr0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_rdaddr1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_wrdata0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_wrdata1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_rddata0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b4_bfu_ctl/mem_rddata1

add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_wr
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_rd
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_wraddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_wraddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_rdaddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_rdaddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_wrdata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_wrdata1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_rddata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b5_bfu_ctl/mem_rddata1

add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_in_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_in_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_in_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_in_1_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_in_ready
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_out_validate
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_out_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_out_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_out_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/thd_od_fft96_32_48/io_out_1_Im

add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_wr
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_rd
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_wraddr0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_wraddr1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_rdaddr0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_rdaddr1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_wrdata0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_wrdata1
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_rddata0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b2_bfu_ctl/mem_rddata1

add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_wr
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_rd
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_wraddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_wraddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_rdaddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_rdaddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_wrdata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_wrdata1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_rddata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b3_bfu_ctl/mem_rddata1

add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_in_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_in_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_in_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_in_1_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_in_ready
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_out_validate
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_out_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_out_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_out_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/sd_od_fft96_32_48/io_out_1_Im

add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_wr
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_rd
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_wraddr0
add wave -color red -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_wraddr1
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_wrdata0
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_wrdata1
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_rdaddr0
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_rdaddr1
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_rddata0
add wave -color ree -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b0_bfu_ctl/mem_rddata1

add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_wr
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_rd
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_wraddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_wraddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_rdaddr0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_rdaddr1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_wrdata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_wrdata1
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_rddata0
add wave -color yellow -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/b1_bfu_ctl/mem_rddata1

add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_in_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_in_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_in_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_in_1_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_in_ready
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_out_validate
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_out_0_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_out_0_Im
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_out_1_Re
add wave -color purple -radix hexadecimal /thd_fft96_tb/u_thd_fft96_32_48/ft_od_fft96_32_48/io_out_1_Im


run 12ms                                                                            

